name: Twistlock
description: Run Twistlock

inputs:
  project:
    description: Specifies a target project
    required: true
  consoleURL:
    description: Prisma Cloud Console's URL
    required: true
  repositoryPath:
    description: The path to the source code to scan.
    required: false
  image:
    description: For a docker image scan, The path to the source code to scan.
    required: false
  githubComment:
    description: Determines if a Github comment within a Pull Request will be created and updated.
    default: true
    required: false
  username:
    description: User for authenticating with Prisma Cloud Console.
  password:
    description: Password for authenticating with Prisma Cloud Console.
  scanPathScope:
    description: Comma separate list of paths where vulnerabilities will fail the workflow.
    required: false
  # twistToken:
  #   description: Token for authenticating with Prisma Cloud Console. Used instead of the username/password.

runs:
  using: "node12"
  main: "dist/index.js"
