name: Create Release Candidate

inputs:
  fromBranch:
    description: 'Source branch name. Ex: develop'
    required: true
    type: string
  toBranch:
    description: 'Destination branch name. Ex: stage'
    required: true
    type: string
  rcBranchPrefix:
    description: 'RC branch prefix name. Ex: stage-release'
    required: true
    type: string
  prTitleHeader:
    description: 'Pull request header. Ex: (Stage)'
    required: true
    type: string
  prLabel:
    description: 'Pull request label. Ex: Stage Release'
    required: true
    type: string
  githubToken:
    description: 'GITHUB_TOKEN'
    default: '${{ github.token }}'

runs:
  using: "composite"
  steps:
    - name: Checkout ðŸ›Žï¸
      uses: actions/checkout@v3
      with:
        token: ${{ inputs.githubToken }}

    - uses: volta-cli/action@v1

    - name: Set RC Branch Name
      shell: bash
      run: echo "rc_branch=$(date +stage-release/hotfix-%Y.%m.%d.%H%M)" >> $GITHUB_ENV

    - name: Create Stage Hotfix RC Branch ðŸ› 
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"
          git fetch --all --unshallow
          git checkout stage
          git pull
          git checkout -b ${{ env.rc_branch }}
          git cherry-pick ${{ github.sha }}
          git push --set-upstream origin ${{ env.rc_branch }}

    - name: Generate Pull Request Body
      shell: bash
      run: |
        echo "ðŸ‘‘ *An automated PR to cherry-pick hotfix to stage* ðŸ‘‘" > pr_msg

    - name: Get Pull Request Body
      id: vars
      shell: bash
      run: echo ::set-output name=pr_body::$(cat pr_msg)

    - name: Create Pull Request ðŸ› 
      uses: repo-sync/pull-request@v2
      with:
        source_branch: ${{ env.rc_branch }}
        destination_branch: ${{ inputs.toBranch }}
        pr_title: '${{ inputs.prTitleHeader }} ${{ env.rc_branch }} '
        pr_body: ${{ steps.vars.outputs.pr_body }}
        pr_label: ${{ inputs.prLabel }}

    - name: Get Pull Request Number
      id: pr-number
      shell: bash
      run: echo "pull_request_number=$(gh pr view --json number -q .number || echo "")" >> $GITHUB_OUTPUT

    - name: Comment on Pull Request
      id: pr-comment
      shell: bash
      run: |
        gh pr comment ${{ steps.pr-number.outputs.pull_request_number }} --body "Merge this PR manually by selecting '**Create a merge commit**' *not* 'Squash and merge'"